apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pod.yaml

configMapGenerator:
  - name: fluent-bit-config
    files:
      - parsers.conf=./parsers.conf
      - fluent-bit.conf=./fluent-bit.conf