version: "3.7"
services:
  fluentd:
    image: fluent/fluent-bit:1.3
    privileged: true
    user: root
    volumes:
      - type: bind
        source: ./
        target: /fluentd/etc
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
    command: /fluent-bit/bin/fluent-bit -c /fluentd/etc/fluentd-bit.conf -v